services:
  postgres:
    image: postgres:13
    ports:
      - 5544:5432
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d odoo"]
      interval: 10s
      timeout: 2s
      retries: 5

  testrunner:
    image: testrunner
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./logs:/opt/odoo/logs
      - ./addons:/opt/odoo/addons
